apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: 3134you/mytom:e73cd7e250573341aab2d2b7ae142d13687e53c3
        ports:
        - containerPort: 8080
        imagePullPolicy: Always


